course_map = {
    "101": "Computers: Apps & Implications",
    "161": "Introduction to Computer Science I",
    "162": "Introduction to Computer Science II",
    "225": "Discrete Structures in CS",
    "261": "Data Structures",
    "271": "Computer Architecture & Assembly Langugage",
    "290": "Web Development",
    "321": "Intro to Theory of Computation",
    "325": "Analysis of Algorithms",
    "331": "Intro Artificial Intelligence",
    "340": "Introduction to Databases",
    "352": "Intro to Usability Engineering",
    "361": "Software Engineering I",
    "362": "Software Engineering II",
    "370": "Introduction to Security",
    "373": "Defense Against the Dark Arts",
    "374": "Operating Systems I",
    "381": "Programming Language Fundamentals",
    "391": "Social & Ethical Issues in Computer Science",
    "399": "ST/Pathways to EECS",
    "406": "Projects",
    "434": "Machine Learning & Data Mining",
    "444": "Operating Systems II",
    "450": "Intro to Computer Graphics",
    "453": "Scientific Visualization",
    "461": "Senior Software Engineering Project",
    "464": "Open Source Software",
    "467": "Online Capstone Project",
    "468": "Inclusive Design (HCI)",
    "469": "Real-World Project Mgmt in CS",
    "472": "Computer Architecture",
    "493": "Cloud Application Development",
    "499": "ST/Empirical Computer Security",
    "501": "Research",
    "510": "Occupational Internship",
    "511": "Programming & Data Structures",
    "514": "Algorithms",
    "515": "Algorithms & Data Structures",
    "544": "Operating Systems II",
    "550": "Intro to Computer Graphics",
    "552": "Computer Animation",
    "553": "Scientific Visualization",
    "559": "ST/Digital Image Processing",
    "568": "Inclusive Design (HCI)",
    "572": "Computer Architecture",
    "579": "ST/Empirical Computer Security",
    "ECE271": "Digital Logic Design",
    "ECE322": "Electronics I",
    "ECE341": "Junior Design I",
    "ECE351": "Signals and Systems I",
    "ECE372": "Intro to Computer Networks",
    "ECE375": "Computer Org & Assembly Lang",
    "ECE390": "Electric and Magnetic Fields",
    "ECE399": "ST/Pathways to EECS",
    "ECE416": "Electronic Materials & Devices",
    "ECE422": "CMOS Integrated Circuits I",
    "ECE431": "Power Electronics",
    "ECE433": "Power System Analysis",
    "ECE451": "Systems Dynamics and Control",
    "ECE461": "Analog & Digital Communication",
    "ECE464": "Digital Signal Processing",
    "ECE468": "Digital Image Processing",
    "ECE472": "Computer Architecture",
    "ECE473": "Microcontroller System Design",
    "ECE499": "ST/Printed & Flexible Electron",
    "ECE516": "Electronic Materials & Devices",
    "ECE522": "CMOS Integrated Circuits I",
    "ECE530": "Contemp Energy Applications",
    "ECE531": "Power Electronics",
    "ECE533": "Power System Analysis",
    "ECE560": "Stochastic Signals & Systems",
    "ECE561": "Analog & Digital Communication",
    "ECE564": "Digital Signal Processing",
    "ECE565": "Estimation, Filtering, Detect",
    "ECE569": "Convex Optimization",
    "ECE572": "Computer Architecture",
    "ECE573": "Microcontroller System Design",
    "ECE580": "Network Theory",
    "ECE590": "Analytical Techqs in Electroma",
    "ECE599": "ST/Printed & Flexible Electron",
    "ECE614": "Semiconductors",
    "ECE621": "Radio Frequency IC Design",
}

data_map = [
    {
        "index": "cs325-index",
        "filename": "CS325_F23.pdf",
        "term": "F23",
        "crn": "325",
        "course_name": "Analysis of Algorithms",
    },
    {
        "index": "cs321-index",
        "filename": "CS321_UN.pdf",
        "term": "unknown",
        "crn": "321",
        "course_name": "Intro to Theory of Computation",
    },
    {
        "index": "cs370-index",
        "filename": "CS370_F23.pdf",
        "term": "F23",
        "crn": "370",
        "course_name": "Introduction to Security",
    },
    {
        "index": "cs271-index",
        "filename": "CS271_F23.pdf",
        "term": "F23",
        "crn": "271",
        "course_name": "Computer Architecture & Assembly Langugage",
    },
    {
        "index": "cs261-index",
        "filename": "CS261_F23.pdf",
        "term": "F23",
        "crn": "261",
        "course_name": "Data Structures",
    },
    {
        "index": "cs290-index",
        "filename": "CS290_S22.pdf",
        "term": "S22",
        "crn": "290",
        "course_name": "Web Development",
    },
    {
        "index": "cs225-index",
        "filename": "CS225_F23.pdf",
        "term": "F23",
        "crn": "225",
        "course_name": "Discrete Structures in CS",
    },
    {
        "index": "cs372-index",
        "filename": "CS372_F23.pdf",
        "term": "F23",
        "crn": "372",
        "course_name": "Intro to Computer Networks",
    },
    {
        "index": "cs362-index",
        "filename": "CS362_F23.pdf",
        "term": "F23",
        "crn": "362",
        "course_name": "Software Engineering II",
    },
    {
        "index": "cs461-index",
        "filename": "CS461_F23.pdf",
        "term": "F23",
        "crn": "461",
        "course_name": "Senior Software Engineering Project",
    },
    {
        "index": "cs361-index",
        "filename": "CS361_F23.docx",
        "term": "unknown",
        "crn": "361",
        "course_name": "Software Engineering I",
    },
    {
        "index": "cs373-index",
        "filename": "CS373_F23.pdf",
        "term": "F23",
        "crn": "373",
        "course_name": "Defense Against the Dark Arts",
    },
    {
        "index": "cs161-index",
        "filename": "CS161_F23.pdf",
        "term": "F23",
        "crn": "161",
        "course_name": "Introduction to Computer Science I",
    },
    {
        "index": "cs340-index",
        "filename": "CS340_F23.pdf",
        "term": "F23",
        "crn": "340",
        "course_name": "Introduction to Databases",
    },
    {
        "index": "cs464-index",
        "filename": "CS464_F23.pdf",
        "term": "F23",
        "crn": "464",
        "course_name": "Open Source Software",
    },
    {
        "index": "cs444-index",
        "filename": "CS444_S22.pdf",
        "term": "S22",
        "crn": "444",
        "course_name": "Operating Systems II",
    },
    {
        "index": "cs493-index",
        "filename": "CS493_F23.pdf",
        "term": "F23",
        "crn": "493",
        "course_name": "Cloud Application Development",
    },
    {
        "index": "cs467-index",
        "filename": "CS467_F23.pdf",
        "term": "F23",
        "crn": "467",
        "course_name": "Online Capstone Project",
    },
    {
        "index": "cs391-index",
        "filename": "CS391_F23.pdf",
        "term": "F23",
        "crn": "391",
        "course_name": "Social & Ethical Issues in Computer Science",
    },
    {
        "index": "cs381-index",
        "filename": "CS381_F23.pdf",
        "term": "F23",
        "crn": "381",
        "course_name": "Programming Language Fundamentals",
    },
    {
        "index": "cs162-index",
        "filename": "CS162_F23.pdf",
        "term": "F23",
        "crn": "162",
        "course_name": "Introduction to Computer Science II",
    },
    {
        "index": "cs450-index",
        "filename": "CS450_F23.pdf",
        "term": "F23",
        "crn": "450",
        "course_name": "Intro to Computer Graphics",
    },
    {
        "index": "cs352-index",
        "filename": "CS352_F23.pdf",
        "term": "F23",
        "crn": "352",
        "course_name": "Intro to Usability Engineering",
    },
]
